// #include "kt_trend_filter.mq5"
// #include "parabolic_sar.mq5"
// #include "perfect_trend_line.mq5"
// #include "stochastic_volatility.mq5"
// #include "volatility_ratio.mq5"
#include "moving_average.mq5"
// #include "macd.mq5"
// #include "stochastic.mq5"
// #include "rsi.mq5"
// #include "trix.mq5"